urls.py
from django.urls import include, path, re_path
from django.views.generic import TemplateView
from rest_framework import routers
from . import views

app_name = "contact"

router = routers.DefaultRouter()
#router.register(r"contact", views.ContactViewSet)

urlpatterns = [
    path("", views.contact_view, name="contact"),
    path("api/list/", views.ContactList.as_view(), name="list"),
    path("api/post/", views.ContactCreate.as_view(), name="create"),
    path("api/", include(router.urls)),
]

models.py
from django.db import models


class Contact(models.Model):
    json = models.JSONField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        if not "email" in self.json:
            return super().__str__()
        return "{}".format(self.json["email"])

views.py
from django.shortcuts import render
from django.conf import settings
from django.core.mail import EmailMessage, send_mail
from django.contrib.sites.shortcuts import get_current_site

from rest_framework import viewsets
from rest_framework import status
from rest_framework import permissions
from rest_framework import authentication
from rest_framework.response import Response
from rest_framework import pagination
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import generics
from rest_framework import filters

import json

from . import models, serializers


class CustomSearchFilter(filters.SearchFilter):
    def get_search_terms(self, request):
        params = request.query_params.get(self.search_param, '')
        params = params.replace('\x00', '')  # strip null characters
        params = params.replace(',', ' ')
        #params = params.translate(str.maketrans({chr(0x0021 + i): chr(0xFF01 + i) for i in range(94)}))
        db_backend = settings.DATABASES['default']['ENGINE'].split('.')[-1]
        if db_backend == 'sqlite3':
            return [json.dumps(param).replace('"', '') for param in params.split()]
        return params.split()

class CustomPagination(pagination.PageNumberPagination):
    page_size = 100
    page_size_query_param = 'page_size'

class ContactList(generics.ListAPIView):
    permission_classes = [permissions.DjangoModelPermissions]
    authentication_classes = [authentication.SessionAuthentication]
    queryset = models.Contact.objects.order_by("-created_at")
    serializer_class = serializers.ContactSerializer 
    filter_backends = [CustomSearchFilter]
    search_fields = ('json',)
    pagination_class = CustomPagination

mail_body = """

※このメールはシステムからの自動返信です

{email}様

お世話になっております。
{site_name}へのお問い合わせありがとうございました。

以下の内容でお問い合わせを受け付けいたしました。管理人が確認いたします

━━━━━━□■□　お問い合わせ内容　□■□━━━━━━

E-Mail：{email}

お問い合わせ内容：{message}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━

———————————————————————
{site_name}
https://{site_domain}/

———————————————————————"""

class ContactCreate(generics.CreateAPIView):
    permission_classes = [permissions.AllowAny]
    queryset = models.Contact.objects.none()
    serializer_class = serializers.ContactSerializer 

    def create(self, request, *args, **kwargs):
        current_site = get_current_site(request)
        site_name = current_site.name
        site_domain = current_site.domain

        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        json = serializer.data['json']
        email = json['email']
        message = json['message']

        email_message = EmailMessage(
            f"【{site_name}】お問い合わせありがとうございます",
            mail_body.format(email=email, message=message, site_name=site_name, site_domain=site_domain),
            f'noreply@{site_domain}',
            [email,],
            [f'contact@{site_domain}',],
            #reply_to=['another@example.com'],
            #headers={'Message-ID': 'foo'},
        )
        email_message.send(fail_silently=False)
        return super().create(request, *args, **kwargs)

def contact_view(request):
    current_site = get_current_site(request)
    site_name = current_site.name
    context = {'is_debug': settings.DEBUG, "site_name": site_name}
    return render(request, 'contact/contact.html', context)

templates/contact/contact.html
{% extends "theme/base.html" %}
{% load static %}

{% block title %}CONTACT | {{ site_name }}{% endblock %}

{% block extra_css %}
{{ block.super }}
{% endblock %}

{% block content %}
{# header #}
{% include 'theme/header.html' %}

<div id="app"></div>

{# footer #}
{% include 'theme/footer.html' %}

{% endblock %}

{% block extra_js %}
{{ block.super }}
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="https://unpkg.com/vue@3.2.22/dist/vue.global{% if not is_debug %}.prod{% endif %}.js"></script>
<script>document.csrf_token = { value: "{{ csrf_token }}" }</script>
<script>axios.defaults.headers.common['X-CSRFToken'] = document.csrf_token.value</script>
<script src="{% static 'contact/js/components/contact_form.js' %}"></script>
<script src="{% static 'contact/js/components/result_modal.js' %}"></script>
<script>
  const App = {
    data() {
      return {
      }
    },
    methods: {
    },
    template: `
      <div class="container">
        <main>
          <div class="py-5 text-center">
            <h2>お問い合わせ</h2>
            <p class="lead">ご質問など下記からどうぞ</p>
          </div>

          <div class="row g-5">
            <div class="col-md-7 col-lg-8">
              <h4 class="mb-3">お問い合わせ</h4>
            </div>
            <contact_form
              url="{% url 'contact:create' %}"
              @created="(data) => {$refs.modal.show(data)}"
            />
          </div>
        </main>

        <result_modal
          ref="modal"
        />
      </div>
    `
  }
</script>
<script>
  const app = Vue.createApp(App)
  app.component('contact_form', contact_form)
  app.component('result_modal', result_modal)
  app.mount('#app')
</script>
{% endblock %}